task: server
http:
  port: 8080
  host: 0.0.0.0
  static_file_dir: ../frontend/dist
servers:
  - host: rpi
    port: 8080
  - host: hella
    port: 8080
  - host: thor
    port: 8080
widgets:
  - name: Bangalore
    type: open_weather_map
    properties:
      apikey: <---insert-api-key-here---->
      units: metric
      lat: 12.9116
      lon: 77.6839